# Generated by Django 4.2.5 on 2023-09-18 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Human',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('apartment', models.CharField(max_length=10, verbose_name='Номер квартиры')),
                ('phone', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=255, verbose_name='Электронная почта')),
                ('settling', models.DateField(auto_now_add=True, verbose_name='Дата заселения')),
            ],
        ),
    ]
